const express = require('express');
const router = express.Router();
const multer = require('multer');
const upload = multer({ dest: 'uploads/' });
const c = require('../controllers/productsController');
const { authenticateStaff, requireRole } = require('../middleware/auth');
router.get('/', c.getProducts);
router.get('/categories', c.getCategories);
router.get('/search', c.searchProducts);
router.put('/rates/bulk', authenticateStaff, requireRole('super_admin','manager'), c.updatePricingTiers);
router.post('/', authenticateStaff, requireRole('super_admin','manager'), c.createProduct);
router.put('/:id', authenticateStaff, requireRole('super_admin','manager'), c.updateProduct);
router.post('/:id/photos', authenticateStaff, requireRole('super_admin','manager'), upload.single('photo'), c.uploadPhoto);
router.delete('/:id/photos', authenticateStaff, requireRole('super_admin','manager'), c.deletePhoto);
router.put('/:id/sizes/:sizeId', authenticateStaff, requireRole('super_admin', 'manager'), c.updateSize);
router.post('/:id/sizes', authenticateStaff, requireRole('super_admin', 'manager'), c.createSize);
router.delete('/:id/sizes/:sizeId', authenticateStaff, requireRole('super_admin', 'manager'), c.deleteSize);
router.delete('/:id', authenticateStaff, requireRole('super_admin'), c.deleteProduct);
router.get('/all', authenticateStaff, requireRole('super_admin','manager'), c.getProductsAdmin);
router.delete('/:id', authenticateStaff, requireRole('super_admin'), c.deleteProduct);
module.exports = router;