const express = require('express');
const cors = require('cors');
const path = require('path');
require('dotenv').config();
const app = express();
app.use(cors());
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use('/uploads', express.static(path.join(__dirname, '../uploads')));
app.use('/api/auth', require('./routes/auth'));
app.use('/api/products', require('./routes/products'));
app.use('/api/categories', require('./routes/categories'));
app.use('/api/settings', require('./routes/settings'));
app.use('/api/orders', require('./routes/orders'));
app.use('/api/addresses', require('./routes/addresses'));
app.use('/api/delivery-boys', require('./routes/deliveryBoys'));
app.get('/api/health', (req, res) => res.json({ success: true, message: 'PackKart API running', version: '1.0.0' }));
app.use((req, res) => res.status(404).json({ success: false, message: 'Not found' }));
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => { console.log('PackKart API running on http://localhost:'+PORT); console.log('Health: http://localhost:'+PORT+'/api/health'); });